### ISSUE TITLE
available for macos

### ISSUE THREAD

**Issue by jorgenspange** [ansible/pylibssh#506] opened 2023-06-14 19:31 UTC
While installing on macos it fails:

````
[jorgenspange@Jorgens-MBP Documents/ansible-network-automation (main) ]$ pip3 install ansible-pylibssh
Defaulting to user installation because normal site-packages is not writeable
Collecting ansible-pylibssh
  Using cached ansible-pylibssh-1.1.0.tar.gz (106 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: ansible-pylibssh
  Building wheel for ansible-pylibssh (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for ansible-pylibssh (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      [1/1] Cythonizing /private/var/folders/3q/9k4kbkrd23d5cqh0lv32spjm0000gn/T/pip-install-361i30jd/ansible-pylibssh_116e4812957149af936655be7c4c8d70/src/pylibsshext/_libssh_version.pyx
      /private/var/folders/3q/9k4kbkrd23d5cqh0lv32spjm0000gn/T/pip-install-361i30jd/ansible-pylibssh_116e4812957149af936655be7c4c8d70/src/pylibsshext/_libssh_version.c:761:10: fatal error: 'libssh/libssh.h' file not found
      #include "libssh/libssh.h"
               ^~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ansible-pylibssh
Failed to build ansible-pylibssh
ERROR: Could not build wheels for ansible-pylibssh, which is required to install pyproject.toml-based projects
````

Would be nice to install pylibssh to macos (apple silicon) via homebrew aswell.

**Comment by webknjaz** [comment] 2024-01-18 15:48
Duplicate of #207.

**Closed as not planned** 2024-01-18 15:48 UTC

**Comment by webknjaz** [comment] 2024-01-18 15:52
You can make the compilation succeed by putting the libssh-dev into the right location, like it's done in our CI.

Refs https://stackoverflow.com/a/75473525/595220
